# @Name: Default
# @List: caskList
export caskList=(

"alfred::Application launcher and productivity software"
"anaconda::Distribution of the Python and R programming languages for scientific computing"
"atom::Text editor"
"bartender::Menu bar icon organizer"
"bettertouchtool::Tool to customize input devices and automate computer systems"
"betterzip::Utility to create and modify archives"
"bitbar::Utility to display the output from any script or program in the menu bar"
"cakebrew::GUI app for Homebrew"
"cleanmymac::Tool to remove unnecessary files and folders from disk"
"dash::API documentation browser and code snippet manager"
"docker::App to build and share containerized applications and microservices"
"dropbox::Client for the Dropbox cloud storage service"
"evernote::App for note taking, organizing, task lists, and archiving"
"figma::Collaborative team software"
"firefox::Web browser"
"font-hack-nerd-font::Developer targeted fonts with a high number of glyphs"
"gitkraken::Git client focusing on productivity"
"google-chrome::Web browser"
"google-cloud-sdk::Set of tools to manage resources and applications hosted on Google Cloud"
"gpg-suite::Tools to protect your emails and files"
"hammerspoon::Desktop automation application"
"hazel::Automated organization"
"hyper::Terminal built on web technologies"
"iterm2::Terminal emulator as alternative to Apple's Terminal app"
"kaleidoscope::Spot and merge differences in text and image files or folders"
"karabiner-elements::Keyboard customizer"
"keybase::End-to-end encryption software"
"kitty::GPU-based terminal emulator"
"launchrocket::Preference pane to manage Homebrew-installed services"
"macdown::Open-source Markdown editor"
"mactex::Full TeX Live distribution with GUI applications"
"mathpix-snipping-tool::Scanner app for math and science"
"mendeley::Research management tool"
"microsoft-office::Office suite"
"ngrok::Reverse proxy, secure introspectable tunnels to localhost"
"notion::App to write, plan, collaborate, and get organized"
"now::"
"openrefine::Tool for working with messy data (previously Google Refine)"
"osquery::SQL powered operating system instrumentation and analytics"
"postman::Collaboration platform for API development"
"provisionql::QuickLook plugin for mobile apps and provisioning profiles"
"qbserve::Automatic time tracker"
"qlcolorcode::QuickLook plug-in that renders source code with syntax highlighting"
"qlimagesize::Display image info and preview unsupported formats in QuickLook"
"qlmarkdown::QuickLook generator for Markdown files"
"qlmobi::Quick Look plugin for Kindle ebook formats"
"qlstephen::QuickLook plugin for plaintext files without an extension"
"qlvideo::Thumbnails, static previews, cover art and metadata for video files"
"quicklook-csv::QuickLook plugin for CSV files"
"quicklook-json::QuickLook plugin for JSON files"
"rocket::Emoji picker optimized for blind people"
"rstudio::Data science software focusing on R and Python"
"steam::Video game digital distribution service"
"todoist::To-do list"
"tor-browser::Web browser focusing on security"
"ubar::Window manager and productivity tool"
"ubersicht::Run commands and display their output on the desktop"
"vagrant::Development environment"
"visual-studio-code::Open-source code editor"
"vlc::Multimedia player"
"xquartz::Open-source version of the X.Org X Window System"
"zoom::Video communication and virtual meeting platform"
"zotero::Collect, organize, cite, and share research sources"
)
